# A short, descriptive name of this building block collection
name: Observable Properties Descriptions

# Short abstract for this collection (optional)
abstract: |
  Building blocks to define schema and ontology options for description of observable properties and how these may be used to augment other standards.

# Description for this collection (optional)
description: |
  Based on I-ADOPT model, with simpler fallbacks as required.
# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.oms.obs-props.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: False

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available